# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcsKfJ81BHrn2NSKZaz_9BtnPmdxW--E

question-3 arithmetic operations
"""

a = int(input())
b = int(input())
add=a+b
difference=a-b
product=a*b
print(add)
print(difference)
print(product)

"""# New Section"""