# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcsKfJ81BHrn2NSKZaz_9BtnPmdxW--E

question-4 division
"""

a = int(input())
b = int(input())
print(a//b)
print(a/b)

"""# New Section"""