# -*- coding: utf-8 -*-
"""dominos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_DJNM77QQOy_G-5eKAV9tkiTHWxB13iG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# Data uploading"""

from google.colab import files

uploaded = files.upload()

"""# reading data"""

df = pd.read_csv("diminos_data.csv")
df.head()

"""# Data Inspection"""

df.shape #number of rows & columns
df.info() #data types & missing values
df.describe() #statistical summary (mean, min, max, quartiles)

"""# Data Cleaning"""

df.isnull().sum() #Remove missing delivery times (if any)

# Convert order_placed_at and order_delivered_at to datetime objects
df['order_placed_at'] = pd.to_datetime(df['order_placed_at'])
df['order_delivered_at'] = pd.to_datetime(df['order_delivered_at'])

# Calculating delivery time in minutes
df['delivery_time'] = (df['order_delivered_at'] - df['order_placed_at']).dt.total_seconds() / 60
df.info()

"""# Analyze Delivery Time Distribution"""

plt.figure(figsize=(8,5))
plt.hist(df['delivery_time'], bins=30)
plt.axvline(31, linestyle='--')
plt.xlabel("Delivery Time (minutes)")
plt.ylabel("Number of Orders")
plt.title("Delivery Time Distribution with SLA Line (31 mins)")
plt.show()

"""# BOXPLOT (OUTLIERS VIEW)"""

#Identify extreme delays
plt.figure(figsize=(6,4))
plt.boxplot(df['delivery_time'], vert=False)
plt.xlabel("Delivery Time (minutes)")
plt.title("Delivery Time Boxplot (Outlier Detection)")
plt.show()

"""# 95th Percentile Calculation (CORE METRIC)"""

p95 = np.percentile(df['delivery_time'], 95)
p95

"""# Average vs Percentile (CRITICAL INSIGHT)"""

mean_time = df['delivery_time'].mean()
p95_time = np.percentile(df['delivery_time'], 95)

mean_time, p95_time

#MEAN vs 95TH PERCENTILE
plt.figure(figsize=(6,4))
plt.bar(['Mean', '95th Percentile'], [mean_time, p95_time])
plt.axhline(31, linestyle='--')
plt.ylabel("Delivery Time (minutes)")
plt.title("Mean vs 95th Percentile Delivery Time")
plt.show()

"""# Late Order Analysis (>31 mins)"""

late_orders = df[df['delivery_time'] > 31]
late_percentage = (len(late_orders) / len(df)) * 100

late_percentage

"""# ON-TIME vs LATE ORDERS"""

labels = ['On Time (≤31)', 'Late (>31)']
sizes = [len(df) - len(late_orders), len(late_orders)]

plt.figure(figsize=(5,5))
plt.pie(sizes, labels=labels, autopct='%1.1f%%')
plt.title("On-Time vs Late Deliveries")
plt.show()

p95_time = np.percentile(df['delivery_time'], 95)

# Plot
plt.figure(figsize=(6,4))
plt.bar(['95th Percentile'], [p95_time])
plt.axhline(31, linestyle='--', label='SLA Limit (31 mins)')

plt.ylabel("Delivery Time (minutes)")
plt.title("95th Percentile Delivery Time vs SLA")
plt.legend()
plt.show()

"""# Peak Hour insights"""

df['order_hour'] = df['order_placed_at'].dt.hour
df.groupby('order_hour')['delivery_time'].mean().plot(kind='bar', figsize=(8,4))
plt.ylabel("Average Delivery Time")
plt.title("Average Delivery Time by Hour")
plt.show()

"""# final conclusion

By focusing on reducing delays during peak periods and managing the worst-performing orders, Kanav can significantly improve compliance, reduce revenue loss, and retain the franchise.
"""