# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcsKfJ81BHrn2NSKZaz_9BtnPmdxW--E

question-6 leap year
"""

def is_leap(year):
    leap = False

    # Write your logic here
    if (year%400==0)or(year%4==0 and year%100 !=0):
        leap= True
    return leap

year = int(input())