# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcsKfJ81BHrn2NSKZaz_9BtnPmdxW--E

question-2  :if else
"""

n=int(input())
if n%2!=0:
    print("Weird")
else:
    if 2<=n<=5:
        print("Not Weird")
    elif 6<=n<=20:
        print("Weird")
    else: #n>20
        print("Not Weird")

"""# New Section"""