# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BcsKfJ81BHrn2NSKZaz_9BtnPmdxW--E

task-1/question-1
"""

print("Hello, World!")



"""# New Section"""